name: local_legacy
description: A Flutter project for local business credit management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.3.0

  # State Management
  provider: ^6.1.1

  # UI & Fonts
  google_fonts: ^6.1.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2
  pretty_qr_code: ^3.0.0

  # PIN Input
  pin_code_fields: ^8.0.1

  # Utils
  crypto: ^3.0.3  # For base64 encoding/decoding
  encrypt: ^5.0.3 # For encryption/decryption

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true